config/routes.rb
Rails.application.routes.draw do

  get 'bookings/:id/index', to: 'bookings#index'
  get 'users/index'
  post 'users/:id/destroy_user', to:'users#destroy_user'
  post 'reviews/add_review'
  post 'reviews/:id/destroy',to: 'reviews#destroy'
  get 'hotels/home'
  root 'hotels#home'
  post '/rate' => 'rater#create', :as => 'rate'
  resources :profiles
  devise_for :users
  resources :rooms do
    get 'bookings/:id/new', to:'bookings#new'
    post 'bookings/:user_id/create', to: 'bookings#create'
    get 'roompictures/index'
    post 'roompictures/add_picture'
    post 'roompictures/:id/remove_picture/', to: 'roompictures#remove_picture'
    post 'roompictures/create'
    post 'roompictures/destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
end

app/models/hotel.rb
class Hotel < ApplicationRecord
	has_many :roooms
	ratyrate_rateable "ambiance", "service", "staff"
	has_many :reviews, dependent: :delete_all
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
	has_attached_file :avatar, styles: {
		thumb: '100x100>',
		square: '200x200#',
		medium: '300x300>'
	}
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :hotel
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
	belongs_to :hotel
	has_many :roompictures, dependent: :delete_all
	validates_numericality_of :floor, less_than_or_equal_to: 10, greater_than: 0
	validates_numericality_of :beds, less_than_or_equal_to: 5, greater_than: 0
	has_many :users, through: :bookings
end

app/models/roompicture.rb
class Roompicture < ApplicationRecord
  belongs_to :room
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  ratyrate_rater
  has_many :reviews, dependent: :delete_all
  has_one :profile, dependent: :delete

  has_many :rooms, through: :bookings
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new,:show,:edit,:update,:destroy]

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.where(user_id:current_user.id)
    if @profile.present?
      redirect_to edit_profile_path(@profile.first.id)
    else
      @profile = Profile.new
    end
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.  id
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.where(user_id:current_user.id).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:user_id, :bio, :username,:avatar)
    end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :check_admin, only: [:edit,:update,:destroy,:new,:create]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.hotel_id = Hotel.last.id
    @room.is_booked = false
    respond_to do |format|
      if @room.save
        format.html { redirect_to rooms_path, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to rooms_path, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @booking = Booking.where(room_id:@room.id).last
    if @booking.present?
      @booking.destroy
    end
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    def check_admin
      if !(current_user.is_admin?)
        redirect_to rooms_path
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:room_number,:floor,:price,:beds,:AC)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/roompictures_helper.rb
module RoompicturesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/profiles/_form.html.erb
<div class="row">
  <div class="col-lg-6 col-xs-6 col-sm-6 col-md-6 text-center 
  col-lg-offset-3 col-xs-offset-3 col-sm-offset-3 col-md-offset-3 text-center">
  <div class="form-group form-signin">
    <%= form_with(model: profile, local: true) do |form| %>
    <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    
    <div class="field">
      <%= form.label :username %>
      <%= form.text_field :username, id: :profile_username,class: 'form-control' %>
    </div>
    <div class="field">
      <%= form.label :bio %>
      <%= form.text_area :bio, id: :profile_bio ,class: 'form-control'%>
    </div>

    <div class="field">
      <%= form.label :avatar %>
      <%= form.file_field :avatar %>
    </div>
    <div class="actions">
      <%= form.submit "Create",class:'btn btn-primary'%>
    </div>
    <% end %>
  </div>
</div>
</div>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profile_path(current_user.id) %>

app/views/profiles/index.html.erb
p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Bio</th>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.user %></td>
        <td><%= profile.bio %></td>
        <td><%= profile.username %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Profile</h1>
<p>
  <%= image_tag @profile.avatar.url(:medium),class:'img-rounded'%>
</p>
<p>
  <strong><%= @profile.username %></strong>
</p>
<p>
  <strong>
  <%= @profile.bio %>
</strong>
</p>
<%= link_to 'Edit', edit_profile_path(@profile),class:'btn btn-primary',style:'color:white' %> 