config/routes.rb
Rails.application.routes.draw do

  get 'bookings/:id/index', to: 'bookings#index'
  get 'users/index'
  post 'users/:id/destroy_user', to:'users#destroy_user'
  post 'reviews/add_review'
  post 'reviews/:id/destroy',to: 'reviews#destroy'
  get 'hotels/home'
  root 'hotels#home'
  post '/rate' => 'rater#create', :as => 'rate'
  resources :profiles
  devise_for :users
  resources :rooms do
    get 'bookings/:id/new', to:'bookings#new'
    post 'bookings/:user_id/create', to: 'bookings#create'
    get 'roompictures/index'
    post 'roompictures/add_picture'
    post 'roompictures/:id/remove_picture/', to: 'roompictures#remove_picture'
    post 'roompictures/create'
    post 'roompictures/destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
end

app/models/hotel.rb
class Hotel < ApplicationRecord
	has_many :roooms
	ratyrate_rateable "ambiance", "service", "staff"
	has_many :reviews, dependent: :delete_all
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
	has_attached_file :avatar, styles: {
		thumb: '100x100>',
		square: '200x200#',
		medium: '300x300>'
	}
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :hotel
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
	belongs_to :hotel
	has_many :roompictures, dependent: :delete_all
	validates_numericality_of :floor, less_than_or_equal_to: 10, greater_than: 0
	validates_numericality_of :beds, less_than_or_equal_to: 5, greater_than: 0
	has_many :users, through: :bookings
end

app/models/roompicture.rb
class Roompicture < ApplicationRecord
  belongs_to :room
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  ratyrate_rater
  has_many :reviews, dependent: :delete_all
  has_one :profile, dependent: :delete

  has_many :rooms, through: :bookings
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :check_admin, only: [:edit,:update,:destroy,:new,:create]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.hotel_id = Hotel.last.id
    @room.is_booked = false
    respond_to do |format|
      if @room.save
        format.html { redirect_to rooms_path, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to rooms_path, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @booking = Booking.where(room_id:@room.id).last
    if @booking.present?
      @booking.destroy
    end
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    def check_admin
      if !(current_user.is_admin?)
        redirect_to rooms_path
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:room_number,:floor,:price,:beds,:AC)
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  def index
  	@users = User.all
  end

  def destroy_user
  	@user = User.find(params[:id])
    @booking = Booking.where(user_id:@user.id).last
    if @booking.present?
      @booking.destroy
    end
  	@user.destroy
  	redirect_to  users_index_path
  end

  private
  def check_admin
  	if !current_user.is_admin?
  		redirect_to root_path
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/roompictures_helper.rb
module RoompicturesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rooms/_form.html.erb
<div class="row">
  <div class="col-lg-6 col-xs-6 col-sm-6 col-md-6 text-center 
  col-lg-offset-3 col-xs-offset-3 col-sm-offset-3 col-md-offset-3 text-center">
  <div class="form-group form-signin">
    <%= form_with(model: room, local: true) do |form| %>
    <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="field">
      <%= form.label :room_number %>
      <%= form.number_field :room_number, id: :room_number ,class: 'form-control'%>
    </div>

    <div class="field">
      <%= form.label :floor %>
      <%= form.number_field :floor, id: :floor,min:1,max:10 ,class: 'form-control'%>
    </div>

    <div class="field">
      <%= form.label :price %>
      <%= form.number_field :price, id: :room_price,class: 'form-control' %>
    </div>
    <h2>Features</h2>
    <hr>
    <div class="field">
      <%= form.label "Number of beds"%>
      <%= form.number_field :beds, id: :bed, min:1,max: 5,class: 'form-control'%>
    </div>
    <div class="row text-center">
      <div class="col-lg-6 col-xs-6 col-sm-6 col-md-6 text-center 
      col-lg-offset-3 col-xs-offset-3 col-sm-offset-3 col-md-offset-3">
      <div class="row">  
        <div class="field">
          <%= form.label "AC" %>
          <%= form.check_box :AC, id: :has_AC ,class: 'form-control'%>  
        </div>  
      </div>
    </div>
  </div>
  <div class="actions">
    <%= form.submit "Submit",class:'btn btn-primary' %>
  </div>

  <% end %>
</div>
</div>
</div>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>
<%= link_to 'Back', rooms_path ,class:'btn btn-warning' %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table class="table">
<thead class="thead-dark text-center">
    <tr>
      <th>Room Number</th>
      <th>Floor</th>
      <th>Beds</th>
      <th>Price</th>
      <th>Ac</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
    <tr>
      <td><%= room.room_number %></td>
      <td><%= room.floor %></td>
      <td><%= room.beds %></td>
      <td><%= room.price %></td>
      <td>
          <% if room.AC? %>
          <%= "Yes" %>
          <% else %>
          <%= "No" %>
          <% end %>
      </td>
      <td><%= link_to 'Picture',room_roompictures_index_path(room.id),class:'btn btn-warning',style:'color:white'%></td>
      <% if current_user.present? %>
        <% if current_user.is_admin? %> 
        <td><%= link_to 'Edit', edit_room_path(room),class:'btn btn-primary',style:'color:white' %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' },class:'btn btn-danger',style:'color:white' %></td>
        <% end %>
        <% if !room.is_booked? %>
        <td><%=link_to 'Book',"/rooms/#{room.id}/bookings/#{current_user.id}/new",class:'btn btn-primary',style:'color:white' %></td>
        <% end %>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.present? %>
  <% if current_user.is_admin? %> 
  <%= link_to 'New Room', new_room_path,class:'btn btn-primary',style:'color:white' %>
  <% end %>
<% end %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @room.price %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

app/views/users/index.html.erb
<h1>Users</h1>
<table class="table">
<thead class="thead-dark text-center">
    <tr>
      <th>User_id</th>
      <th>Email</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <% if !user.is_admin? %> 
    <tr>
      <td><%= user.id %></td>
      <td><%= user.email %></td>
      <% if current_user.is_admin? %> 
      <td><%= link_to 'Destroy', "/users/#{user.id}/destroy_user", method:'post', data: { confirm: 'Are you sure?' },class:'btn btn-danger',style:'color:white' %></td>
      <% end %>
      <% end %>
    </tr>
    <% end %>

  </tbody>
</table>