config/routes.rb
Rails.application.routes.draw do

  get 'bookings/:id/index', to: 'bookings#index'
  get 'users/index'
  post 'users/:id/destroy_user', to:'users#destroy_user'
  post 'reviews/add_review'
  post 'reviews/:id/destroy',to: 'reviews#destroy'
  get 'hotels/home'
  root 'hotels#home'
  post '/rate' => 'rater#create', :as => 'rate'
  resources :profiles
  devise_for :users
  resources :rooms do
    get 'bookings/:id/new', to:'bookings#new'
    post 'bookings/:user_id/create', to: 'bookings#create'
    get 'roompictures/index'
    post 'roompictures/add_picture'
    post 'roompictures/:id/remove_picture/', to: 'roompictures#remove_picture'
    post 'roompictures/create'
    post 'roompictures/destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
end

app/models/hotel.rb
class Hotel < ApplicationRecord
	has_many :roooms
	ratyrate_rateable "ambiance", "service", "staff"
	has_many :reviews, dependent: :delete_all
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
	has_attached_file :avatar, styles: {
		thumb: '100x100>',
		square: '200x200#',
		medium: '300x300>'
	}
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :hotel
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
	belongs_to :hotel
	has_many :roompictures, dependent: :delete_all
	validates_numericality_of :floor, less_than_or_equal_to: 10, greater_than: 0
	validates_numericality_of :beds, less_than_or_equal_to: 5, greater_than: 0
	has_many :users, through: :bookings
end

app/models/roompicture.rb
class Roompicture < ApplicationRecord
  belongs_to :room
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  ratyrate_rater
  has_many :reviews, dependent: :delete_all
  has_one :profile, dependent: :delete

  has_many :rooms, through: :bookings
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/roompictures_helper.rb
module RoompicturesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
       <p class="copyright text-muted small">Copyright &copy; Your Company 2014. All Rights Reserved</p>
     </div>
   </div>
 </div>
</footer>

app/views/layouts/_nav.html.erb
  <div class="container-fluid text-center" style="background: url('/images/background1.jpg'); background-size:initial;">
    <h1 style="font-size: 65px;"> <b> Shahi Ghar </b></h1>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <nav class="navbar navbar-inverse" role="navigation" style="background: transparent; border-color: transparent;" >
      <div class="container" style="width:100%">
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="row">
          <div class="col-lg-12 text-center ">
             <ul class="nav nav-justified color">
                <li>
                    <%= link_to "Home",hotels_home_path %>
                </li>
                <li>
                    <% if current_user.present? %>
                    <% if current_user.profile.present? %>
                    <%= link_to "Profile",profile_path(current_user.id)%>
                    <% else %>
                    <%= link_to "Profile",new_profile_path%>
                    <% end %>
                    <% end %>
                </li>
                <li>
                    <%= link_to "Rooms",rooms_path %>
                </li>
                <li>
                    <% if current_user.present? %>
                    <%= link_to "Booking","/bookings/#{current_user.id}/index"%>
                    <% end %>
                </li>
                <% if current_user.present? %>
                <% if current_user.is_admin? %>
                <li>
                    <%= link_to "User",users_index_path %>
                </li>
                <% end %>
                <% end %>
                <li>
                    <% if current_user.present? %>
                    <%= link_to "Sign Out",destroy_user_session_path, method: 'delete' %>
                    <% else %>
                    <%= link_to "Sign In",new_user_session_path %>
                    <% end %>
                </li>
            </ul>
        </div>
    </div>
    <!-- /.navbar-collapse -->
</div>
<!-- /.container -->
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>CloudProject</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<%= render 'layouts/nav' %>
	<div class="container center">
		<div class="row">
			<div class="col-lg-12 col-xs-12 col-sm-12 col-md-12 text-center">
				<%= yield %>
			</div>
		</div>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>